### ISSUE TITLE
vadiiiiiim spisok ne rabotaet

### ISSUE THREAD

**Issue by mur073** [rusyaev-dk/msu_7_group_practice#2]
Владимир - СП-шник удалой,
Весь день сидит, склонясь над кодом.
Дебажит, пишет с головой,
Забыв про сон и про погоду.
Алгоритмы - его стихия,
Структуры данных - лучший друг.
Контесты - главная стратегия,
Чтоб стать он мог гуру наук.
Но вот беда - пришла девчонка,
Позвала в кино, гулять, мечтать.
А наш герой, смутившись только,
Сказал: "Мне надо посылать!"
Она в слезах, не понимая,
Что посылать он хочет код.
А Вова, время не теряя,
Уж запустил свой компилятор!

**Comment by rusyaev-dk** [comment]
Считаю стихотворение удовлетворительным ответом. А теперь - за работу, ребятки)
